server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/llot
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


llot:
  mqtt:
    login:
      username: admin
      password: 20010904